### ISSUE TITLE
Establish We Are Thought Fox routines and regular tasks

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/wearethoughtfox-wp#1]
"BLOGGING IS NOW MANDATORY."
- Weeknotes 
- Weekly links (share things that interest us)
- Google Hangout once a week to discuss what we're all up to - how about Tuesdays?

**Comment by UnaJanicijevic** [comment]
eep! It's getting serious ;)

**Comment by robertocarroll** [comment]
ha! I'd forgotten I wrote this one. It does sound a onerous ... but hopefully it will be fun!
