### ISSUE TITLE
Logo needs incorporating into the nav when not on homepage

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/wearethoughtfox-wp#10]

**Comment by UnaJanicijevic** [comment]
There is a design for a mini header on p3 of the InDesign doc. Does that work?

**Comment by robertocarroll** [comment]
I think it's a bit big. What do you reckon? 
See:
https://github.com/robertocarroll/wearethoughtfox/issues/7#issuecomment-20884820

**Comment by clintmclean** [comment]
I agree it takes up a lot of screen real estate.

**Comment by robertocarroll** [comment]
I'm going to close this issue as it is covered in issue https://github.com/robertocarroll/wearethoughtfox/issues/7#issuecomment-20916174
