### ISSUE TITLE
About Us text

### ISSUE THREAD

**Issue by clintmclean** [wearethoughtfox/wearethoughtfox-wp#12]
We Are Thought Fox loves media. Great projects require fresh ideas, carefully crafted content, brave design and a bulletproof back-end. We thrive on bringing all the elements together to create effective and memorable websites, apps, videos, maps and more.

**Comment by robertocarroll** [comment]
I liked the phrase "an agency for digital culture" ... and I'm not sure about "love media" cf "design media" as a description that will resonate. I've put the old one here for comparison ... 

WE ARE THOUGHT FOX is an agency for digital culture, working with organisations to plan and create media for the 21st century. We design media: websites, apps, videos, maps and more.

**Comment by clintmclean** [comment]
Yeah I am with you on the 'love media" actually. We can rework that text. I was thinking we shouldn't repeat the same text we have on the home page  - which says "an agency for digital culture" but maybe that is flawed thinking since not everyone will see the home page.

**Comment by clintmclean** [comment]
Here's a suggestion. I will put it on the site 'cause I want to see length but we can keep talking about it.

WE ARE THOUGHT FOX is an agency for digital culture, working with organisations to plan and create media for the 21st century. Great projects require fresh ideas, carefully crafted content, brave design and a bulletproof back-end. We bring these elements together to create effective and memorable websites, apps, videos, maps and more. We design media.

**Comment by robertocarroll** [comment]
Sounds good. My only quibble is that the roadmap laid out in the middle of the para is quite prescriptive and presumes a certain type of project.

**Comment by clintmclean** [comment]
How about this? It is less specific about these things being all part of one project but rather a list of skills we bring.

WE ARE THOUGHT FOX is an agency for digital culture, working with organisations to plan and create media for the 21st century. Through our international experience, we produce fresh ideas, carefully crafted content, brave design and bulletproof code. We bring these elements together to create effective and memorable websites, apps, videos, maps and more. We design media.

**Comment by robertocarroll** [comment]
Great! I've added it in and closing this issue now. (Feel free to re-open it if you have more to discuss)
