### ISSUE TITLE
Team photos

### ISSUE THREAD

**Issue by clintmclean** [wearethoughtfox/wearethoughtfox-wp#13]
We need to all take a portrait of ourselves for our bios. It is important these look very consistent. Let's do it on white and we can change bkgnd colour if necessary (white bkgnd on white page of the site isn't ideal)

I will shoot one as a reference to match to. I will use only daylight so we can hopefully match to a reasonable degree. 

Do you have a camera with manual controls Rob?

**Comment by UnaJanicijevic** [comment]
Sure sound good. Eye contact right?

**Comment by robertocarroll** [comment]
Sounds like a plan. I have a Canon 550d. Is that OK?

**Comment by clintmclean** [comment]
yep that's totally fine. I will send samples today or tomorrow.
I think casual is the key. ...and definitely clothes on.
