### ISSUE TITLE
Home Page Featured Image(s)

### ISSUE THREAD

**Issue by clintmclean** [wearethoughtfox/wearethoughtfox-wp#14]
I put a new thunderbolt monitor in the featured spot to see if the more panoramic frame may work better for our space (let us show a bit of what's below the featured section).

Not sure if it is better...maybe? We can revert back easily enough.

Rob - how will we do the other two images that appear above the text on the design?
Can a slideshow go inside the frame? The alternative is to reload the whole page to see  the next image? Would the slideshow hold three images in three monitors with their nav being the thumbnails? So many questions...

**Comment by robertocarroll** [comment]
Do you want the two small images (as in the design)? 

Or would you prefer a slideshow? 

Which would be best? Both are possible - but the hybrid solution  - the last one you mention of somehow making the top two images thumbs for the slideshow would be the least preferable for me.

**Comment by UnaJanicijevic** [comment]
I'm thinking we can ditch the small images in favour of the slideshow.
One things we should think about is the length of the text. It really shouldn't go below the image. So either we live with smaller type, edit or cut it off with a 'more' button.
Also we should set-off the segments of the project "logo, branding" in lighter weight/italic....

**Comment by robertocarroll** [comment]
You can control the text length using the "excerpt" field, so it can be customised to fit.

**Comment by robertocarroll** [comment]
I've made it so that if there's a slideshow, it will now show on the homepage instead of the image. 

To add a slideshow, go to the post and put a custom field called slideshow and then the number of the slideshow from Royal Slider.

**Comment by clintmclean** [comment]
Got it.

**Comment by clintmclean** [comment]
I've added the slideshow and an excerpt - not sure how to do the 'more' link.
Maybe we need more height on the slideshow proportions so we can use more of the slideshow area with average horizontal images?

**Comment by robertocarroll** [comment]
The setting is in Royal Slider on a per slideshow basis in the size and scaling options. I've changed the height to 600px. Better?

**Comment by clintmclean** [comment]
thanks yeah i think so. I suspect we'll tweak it a bit as we use it but it's a good starting point I think. Una?

**Comment by UnaJanicijevic** [comment]
works for me!

**Comment by robertocarroll** [comment]
Closing this issue since it seems to be resolved.
