### ISSUE TITLE
Update! July 16 meeting with Mandy and Suheyla

### ISSUE THREAD

**Issue by clintmclean** [wearethoughtfox/wearethoughtfox-wp#16]
It's that time again. Update day!

I met with Mandy and Suheyla yesterday. I think Suheyla is going to be good to work with on future things - she seems very organized and on the ball - and speaks arabic which will help with some our work.

I have good news and also good news from yesterday. I will start with the good news.
1. Rob - though the Arabic for the site is not going to be ready for a while - perhaps quite a while - it is no longer part of our previous project but will be charged as a separate project. We haven't discussed exactly how much, and it will be somewhat discounted since it was originally part of the project they have already paid for, but it will be paid. 
2. Sharjah proposal: Mandy and Suheyla are both keen on this and Sultan has now gone over the proposal and has asked for a brief he can use to try to get us some more interest.

And in other news:
Sultan is going away to study in some programme at Stanford for all of August so anything he needs to be involved in will not likely happen until after that - though I am sending him the brief today and he will start sending that around.
1. The website for him and for his deceased friend Thamer are stalled. It is Ramadan now and then Sultan is away so nothing until Sept at least. His site is less of a priority so I suspect it will be in the new year.
2. There is a new exhibition and catalogue due to launch in Feb or March. I don't know exactly what we'll be doing for this but at least the catalogue and putting new content on the site. We are supposed to have content by Nov/Dec

**Comment by UnaJanicijevic** [comment]
I love conversations that start with "Do you want the good news or the good news?"
Thanks Clint. Yay.

**Comment by robertocarroll** [comment]
Great update. I'm going to close this issue.
