### ISSUE TITLE
UPDATE ! July 21 hang out minutes

### ISSUE THREAD

**Issue by clintmclean** [wearethoughtfox/wearethoughtfox-wp#18]
**Twitter:** 
Clint and Una will populate. 

**Blog:**
Una will write about magazine design
Rob will finish at least one of his
Clint will try to think of something. 

**Work section on home page**
Will become two rows of three 
Clint will add at least one more project
Una will add one project?

**Work section home page #2**
Clint will test to see if excerpts are working

**Images**
Send all images to Clint who will put them in tablet frames etc
Una - send Clint illustrator magazine template

**Portraits**
Shoot portraits on white - candid and 'normal'

**Footer/Contact**
new design - deeper with text closer to top of the section
Need a couple 'Did You Know' items for interesting facts. Based on us/watf

**Design**
Need design for single blog item page
Need design for all work page (or was that covered already?)
Need design for single work item

**Excerpts**
Excerpt on feature project may need to be done differently as it is long when compared to excerpts on secondary projects. Rob?

_**Please add anything I have missed**_

**Comment by robertocarroll** [comment]
I think we've covered most of these and the ones we haven't have open issues, so I'm closing this issue.
