### ISSUE TITLE
Templates for pitches and documentation

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/wearethoughtfox-wp#2]
Standard templates so all our pitches and documentation look the same.

**Comment by UnaJanicijevic** [comment]
Good idea, I can develop those. The Barjeel branding presentation template was with the old branding, so we need a new one! The next pitch we do, will be my chance to standardize—perhaps the Sharjah Tourism one, Clint?

**Comment by clintmclean** [comment]
The Sharjah one is already sent so we'll need to wait for the next one (Hopefully Tashkeel) to put into practice.

I can work on a break down of the structure of the proposal. I suspect the content will be something we refine over and over again as we learn from what is working and from our mistakes.
