### ISSUE TITLE
Borders on content, eg work, blog, (as in the Indesign file)

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/wearethoughtfox-wp#23]
The problem with right and left borders is that they take the height from the content so it is not possible to keep the height uniform (as in your design) very easily.

**Comment by clintmclean** [comment]
Should we do the content on 'cards' so to speak as we talked about near the end of Barjeel so we don't have alignment issues? Whether the cards are visible as such or not, we need a container to maintain alignment for multiple rows.

**Comment by robertocarroll** [comment]
Sorry I can't remember what the "cards" were, but let's close this now and pick it up in the next sprint.

**Comment by robertocarroll** [comment]
Actually I'm going re-open and move out of this milestone.

**Comment by robertocarroll** [comment]
I've added borders on the about us, but the border looked odd on the Twitter. Also it's quite a lot of work to add borders on the work posts as in the design file, so I've left it ... Let's open a new issue about cards and revisit the design as well.
