### ISSUE TITLE
Round-up from UNA

### ISSUE THREAD

**Issue by clintmclean** [wearethoughtfox/wearethoughtfox-wp#25]
1• New girl to put in place (Clint I will look at the new files you sent)
2• Can we lose the paragraph break after 'culture' below the logo.
3• Nav: WHO WE ARE (right now it's who are we... as if it's a question)
4• Slideshow needs white background
5• Barjeel description on the secondary page: I think a few things are redundant there, so I would just say Logo and branding applications, website design and development, online archive, exhibition catalogue, promotional materials
6• More work: Photography, thumbnail image is bigger than the others. Can we lead with another just because that one doesn't have an ipad frame so it'll be better in the mix. Also description is much longer than the others
7• Yes, we'll need an image for the guest. The back of someone's head? Or something more clever?
8• Twitter: If we start tweeting, will the area between the log posts self-populate?
9• On the secondary pages, like Blog and Work, I find the titles to be too big. Way bigger than anything else on the site.

**Comment by clintmclean** [comment]
8 What is the status of this?
9 Is this resolved?

NEED ROB"S PHOTO

NEW
10. Need to style the home page Barjeel text. Can this be done without it affecting the styling on other page using the same text?
11. need figure in the footer.
12. need to style footer - Una can you look after that? "Register in..." info and logo to bottom of page at least?
13. need two rows of work on home page to make section approx same size as others - OR are we leaving as is?
14. Can we update the ceebeebies blog a bit so it isn't old info from august 2012?

**Comment by robertocarroll** [comment]
1. I've added a widget called blog-middle. You need to put the twitter embed code in there if you want to show the twitter stream. 
2. Yes - I've made these titles smaller. 

Photo will come tomorrow. I need to de-beard ... 
1. See https://github.com/robertocarroll/wearethoughtfox/issues/21
2. Who's doing this and where does it need to go? 
3. What's this? 
4. Suggest leave for now ...
5. Added a new blog post.

**Comment by clintmclean** [comment]
I sent you the png for the footer - it goes with the Fun Fact.

Isn't our footer a bit unfinished in terms of placement of things still? I thought it was just roughed in. 
We should add our personal individual emails on there as well as the general one too I think.

**Comment by robertocarroll** [comment]
Contact details in the footer are editable in the footer contact widget.

**Comment by robertocarroll** [comment]
I think we've covered most of this so closing the issue.
