### ISSUE TITLE
UPDATE!

### ISSUE THREAD

**Issue by UnaJanicijevic** [wearethoughtfox/wearethoughtfox-wp#26]
Clint your email is bouncing back, so here is what I just sent re: tashkeel and another potential project.

"Too bad about Tashkeel, but even the projects that don't work out get our name out there...

In other news, I'm meeting with the this woman Aliyah Shamsher next week about a potential project.
She's the former editor of ELuxe (online fashion emporium, canadian version of net-a-porter) and she's stepping out on her own, doing another online fashion based thing. She needs a web 'designer' but that could mean a variety of things, so I am going to scope it out."

**Comment by clintmclean** [comment]
Strange - I did receive it but internet is being weird so...

Tashkeel is still not dead. I think if she is able to get our proposal under consideration at this sort of late stage, that we'll be in the running. It is a matter of whether the bosses want to consider a new entry... there is hope. And as you say, it gets our name out there - and maybe if the people they hire don't work out as happened with Barjeel originally...

**Comment by clintmclean** [comment]
oops I wrote that in the wrong place...sort of.

That sounds potentially exciting with the Eluxe woman. Even if it is strictly design, it could be an exciting project for you.

**Comment by robertocarroll** [comment]
Yes. The Eluxe sounds promising. Good luck. Closing this issue now.
