### ISSUE TITLE
Last minute tweaks

### ISSUE THREAD

**Issue by UnaJanicijevic** [wearethoughtfox/wearethoughtfox-wp#27]
Hey guys, here are a few things I see.
Let me know what's fixable at this stage.
1. Alignment of Barjeel Description and slide show. Description pokes up above the slideshow
2. Slideshow. I think it's weird to interrupt the website slides with branding. It should go first or last I think.
3. More work: Photography item still has a bigger thumbnail. And I think it should go between the ones with ipad screens. ie. second.
4. Blog secondary page: center headline. Also as requested yesterday, please make it smaller.
5. Footer: Stop scrolling at the beginning of the grey box to avoid logo overlap.
   Can we make the "registered in..." line much smaller. 
   Clint wanted to add direct emails there. Should we do:

LONDON: +44 7523 234 831
rob@wearethoughtfox.com

DUBAI: + 000000000000
clint@wearethoughtfox.com

TORONTO: +1 416 918 6256
una@wearethoughtfox.com
(where do these emails go? Can I have a redirect to una@mac.com)

I would skip the general email then. Also, I think we should do FB, TWITTER, LINKEDIN with grey icons. Let me know if you have those, or need me to provide.

Thanks!

**Comment by robertocarroll** [comment]
1. This is due to the varying image dimensions (see how image 2 aligns). I've added a bit of margin to the top. 
2. I've centred and reduced font size even more (I reduced it yesterday as well). 
3. Not possible to stop scrolling. Contact details can be edited in the footer contact widget. 

(That's all I can do until the morning - then not much time ... sorry)

**Comment by robertocarroll** [comment]
Closing this issue now. If you want to carry anything over that I've missed please can you open another issue and put it in the post-launch milestone. Thanks!
