### ISSUE TITLE
Versions of the intro text

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/wearethoughtfox-wp#32]
We Are Thought Fox is an agency for digital culture, working with organisations to plan and create media. We produce fresh ideas, carefully crafted content, brave design and bulletproof code. We bring these elements together to create effective and memorable websites, apps, videos, maps and more. We design media.

**Comment by robertocarroll** [comment]
We Are Thought Fox is an agency for digital culture, working with organisations to plan and create digital and print media. Websites, magazines, prototypes, videos, maps and more. We help organisations explore the possibilities new formats, devices and experiences offer their users. We design media.

**Comment by UnaJanicijevic** [comment]
Another version to bat around.

We Are Thought Fox is a multi-disciplinary creative agency. We produce fresh ideas, carefully crafted content, brave design and bulletproof code. We bring these elements together to create effective and memorable websites, apps, videos, maps and more. Our team is global (based in Dubai, London and Toronto) but our approach is local. 

I think as we re-think the website, or at least its function, we should stress the fact that we have a team based in various places (doing lots of stuff individually) but like superheroes when called to a task we assemble our skills to produce cool things together. I don't think that last sentence quite says that, but it's a start.
I think that's what sets us apart—flexibility and roots in different places. Also explains why we're not so active on our own site.

ps. For Clint: The Grid just folded. :(

**Comment by robertocarroll** [comment]
I forgot you were signed up to updates. Thanks for the new version. I like it ... I've moved it to a thing called Poetica which I've always wanted to try for collaborative editing ... Let me know if you think that's a good idea.
