### ISSUE TITLE
Foreign Policy pitch

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/wearethoughtfox-wp#33]
> As part of our newly redesigned magazine, FP now features a data feature in each issue, and we're putting out an open call for pitches from data journalists. The feature, Decoder, is a two-page spread in the print mag with an online component. It's somewhat loosely defined -- the hard and fast parameters being that it 1) is a story based in the data and 2) fits in our coverage wheelhouse: global politics, economy, war, peace, development, etc.

**Comment by robertocarroll** [comment]
## Idea 1

Map of biggest refugee camps - c.f. the size - photos from above and in the context of a user's location. - - http://berglondon.com/projects/dimensions/ 
- http://prisonmap.com/
- http://crisis.net/explore/
- http://www.smithsonianmag.com/innovation/where-are-50-most-populous-refugee-camps-180947916/?no-ist
- http://www.theguardian.com/world/gallery/2015/feb/03/the-daily-planet-satellite-images-from-google-earth-in-pictures#img8

Use https://github.com/Leaflet/Leaflet.draw to create vector outlines and then overlay them on the map according to user's location.

**Comment by robertocarroll** [comment]
## Idea 2

Something to do with remittances. Revealing the size and the paths the money takes.

**Comment by robertocarroll** [comment]
## Idea 3

This chart about Islam in Europe was interesting: 
http://www.economist.com/blogs/graphicdetail/2015/01/daily-chart-2

**Comment by clintmclean** [comment]
two data sets about prison:

1.
http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies/4572?q=&paging.rows=25&sortBy=10
t
Data: correctional facilities
http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies?keyword=correctional+facilities&permit%5B0%5D=AVAILABLE
, correctional facilities (adults)
http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies?keyword=correctional+facilities+%28adults%29&permit%5B0%5D=AVAILABLE
, corrections
http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies?keyword=corrections&permit%5B0%5D=AVAILABLE
, criminal histories
http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies?keyword=criminal+histories&permit%5B0%5D=AVAILABLE
, drug abuse
http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies?keyword=drug+abuse&permit%5B0%5D=AVAILABLE
, HIV
http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies?keyword=HIV&permit%5B0%5D=AVAILABLE
, inmate classification
http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies?keyword=inmate+classification&permit%5B0%5D=AVAILABLE
, inmate deaths
http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies?keyword=inmate+deaths&permit%5B0%5D=AVAILABLE
, inmate populations
http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies?keyword=inmate+populations&permit%5B0%5D=AVAILABLE
, inmate programs
http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies?keyword=inmate+programs&permit%5B0%5D=AVAILABLE
, inmates
http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies?keyword=inmates&permit%5B0%5D=AVAILABLE
, offenses
http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies?keyword=offenses&permit%5B0%5D=AVAILABLE
, prison conditions
http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies?keyword=prison+conditions&permit%5B0%5D=AVAILABLE
, substance abuse
http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies?keyword=substance+abuse&permit%5B0%5D=AVAILABLE
,treatment programs
http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies?keyword=treatment+programs&permit%5B0%5D=AVAILABLE
1. http://www.tdcj.state.tx.us/death_row/dr_executed_offenders.html
   Data: last statement of everyone executed  in the Texas from 1982 until now.

Idea 2 - drones are being used with standard and infrared cameras to create
spacial data maps of archaeological sites. Very new trend revolutionizing
surveying (according to an archaeologist specialising in drone surveying.

**Comment by robertocarroll** [comment]
Random ideas:
- Borders 
- http://www.bloombergview.com/articles/2015-06-18/the-irony-of-hungary-s-border-wall
- http://www.theguardian.com/world/ng-interactive/2013/nov/walls#intro
- http://frontex.europa.eu/assets/Publications/Risk_Analysis/Annual_Risk_Analysis_2015.pdf
- http://www.economist.com/blogs/graphicdetail/2015/09/daily-chart-10#comments
- http://www.ashgate.com/isbn/9781472429667
- http://dandurand.uqam.ca/evenements/appels-de-communications/1124-borders-walls-and-security.html
- https://github.com/madewulf/MigrationsMap.net
- Overlays https://www.flickr.com/photos/stml/sets/72157612286408153
- http://frontex.europa.eu/trends-and-routes/migratory-routes-map/

Perhaps combine the borders, routes and walls together. 
- wiki edits: http://wikistream.wmflabs.org/#background=false&namespace=article&robot=false&wiki=en.wikipedia
- remittances: http://econ.worldbank.org/WBSITE/EXTERNAL/EXTDEC/EXTDECPROSPECTS/0,,contentMDK:22759429~pagePK:64165401~piPK:64165026~theSitePK:476883,00.html#Remittances
  http://www.pewsocialtrends.org/2013/12/17/changing-patterns-of-global-migration-and-remittances/4/#chapter-4-remittances
- living in the electromagnetic spectrum - we exist at different frequencies
  not cameras - images made from data - what’s changed in 40 years?
  construction, assembledge, distribution - a guide  
  See Rainbow planes  http://www.offroaders.com/info/rainbow-airplane-hyde-park.jpg (artifacts of different parts of the spectrum).
  Also cross referencing different parts of a person's digital identity to build a full profile: https://theintercept.com/2015/09/25/gchq-radio-porn-spies-track-web-users-online-identities/
