### ISSUE TITLE
Web Fonts from Cloud,Typography

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/wearethoughtfox-wp#4]
Brand fonts cannot be used with @font-face. 

The only way to use Gotham seems to be with their "cloud typography" which starts at $99 per year subscription:

http://www.typography.com/faq/category.php?topicID=10

UNA: I think the H&FJ cloud type licence is the best plan. That way we keep our core typeface Gotham. I have 2 other slab serif typefaces from H&FJ (Sentinel & Archer) that look similar to Jubilat, so we can go with one of those.

**Comment by robertocarroll** [comment]
I've bought the $99 subscription at Hoefler & Frere-Jones. We've got to be a bit careful about choosing fonts because "the first five fonts are free", but it seems you can't change your mind: 

http://www.typography.com/cloud/user-guide/included

So do we want the Gotham Screensmart:
http://www.typography.com/fonts/gotham/styles/screensmart/

And Sentinal Screensmart:
http://www.typography.com/fonts/sentinel/styles/screensmart/

**Comment by UnaJanicijevic** [comment]
Yes, Gotham & Sentinel. 
They are versatile and I'm sure will prove useful for other projects too.

**Comment by robertocarroll** [comment]
Thanks. I've added the webfonts. Need to clean up some of the weights.
