### ISSUE TITLE
Site structure / Templates required 

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/wearethoughtfox-wp#7]
1. Homepage 

> Work (internal anchor - goes down page - click for more) 
> About (internal anchor - goes down page)
> Blog (internal anchor - goes down page - click for more)
> Contact  (internal anchor - goes down page)
1. Blog 
   (Archive of all blog posts)
2. Work 
   (Archive of all work posts)

**Comment by robertocarroll** [comment]
It's currently working in this way. Another option would be to include the about and contact on every page and a click on that in the nav will take the user to that section.

**Comment by robertocarroll** [comment]
The contact footer also needs to be deeper to allow for the scroll to reach it.

**Comment by clintmclean** [comment]
I think the grey nav bar needs to sit at the top of each page so there is always an indicator for which page you are on and so you can move to a different page. I agree the logo would make sense to be visible too but how do we do that without having a header on each front page section?

**Comment by robertocarroll** [comment]
I agree the nav bar needs to sit on the homepage, but not so sure about the other pages. I've fixed it once you scroll past it on the homepage. 

How about using the initials logo (see attached) in the centre of the nav? The logo needs to be small so it doesn't take up much height, but the full logo can't go very small due to the need to read it ... That's my logic, at least ... 

![logo-abbr](https://f.cloud.github.com/assets/1565953/789110/ebfc2adc-eb09-11e2-80dc-5f1cb3e68f99.jpg)

**Comment by clintmclean** [comment]
I think it would be too small. I like the nav bar like that though - very tasteful. Maybe the bar needs to be twice that depth though to make it practical to put the logo in? The logo could stick out below the bar if we added some padding so it doesn't overlap content. Maybe?

**Comment by robertocarroll** [comment]
This is the kind of thing I had in mind:

![web design web development mobile content strategy by happy cog](https://f.cloud.github.com/assets/1565953/792467/5784cb9e-eb9e-11e2-9603-a05995507f3b.png)

They have almost exactly the same approach - a big header on the homepage which goes to links in the page and then a different nav with no big header on the rest of the website. 

http://happycog.com/

**Comment by UnaJanicijevic** [comment]
how bout like this, with our acronym logo?

![screen shot 2013-07-13 at 12 42 17 pm](https://f.cloud.github.com/assets/4991415/793059/6d6e5712-ebdb-11e2-9604-56f8d636947f.png)

**Comment by UnaJanicijevic** [comment]
Could do this for footer too, if we want it to be more minimal.

**Comment by clintmclean** [comment]
Fine by me. Should we lose the white outline on our logo since it only appears over the grey? Does it look funny?

**Comment by UnaJanicijevic** [comment]
The white box gives the girl something to come out of. I think we need it. Plus I like it. ;)

**Comment by clintmclean** [comment]
oh I just mean on the acronym logo in the header you just added. I am just wondering if because it is a white outline on white mostly, whether we should lose it and let the triangle just sit on the grey header bar. ...I am not sure, just wondering out loud.

**Comment by UnaJanicijevic** [comment]
I think it's better the other way
but here it is so you can see. It emphasizes that white outline cut-off-corner-triangle around the T in a strange way.

![screen shot 2013-07-13 at 3 17 39 pm](https://f.cloud.github.com/assets/4991415/793265/f865b7c4-ebf0-11e2-85a2-c993f0a175ad.png)

**Comment by clintmclean** [comment]
yeah ok I agree the other way is better. Is it just me about that edge? Worth thinking about putting it on a white box with a faint outline like the girl logo? If I'm the only one thinking it's odd then it's fine - I'm not going to lose sleep over it.

**Comment by UnaJanicijevic** [comment]
Yea I tried that first, but then the grey bar has to be really thick so that the white box doesn't bleed into the white background. Not so nice looking.

**Comment by robertocarroll** [comment]
Thanks for this. I'll build it. Una: any chance you could send the logo with the white around it. Thanks!

**Comment by UnaJanicijevic** [comment]
![logo-small](https://f.cloud.github.com/assets/4991415/798901/45c19e50-ed6a-11e2-8c3f-9a9ea7a865d6.png)
Here is a PNG, larger than you need.

**Comment by robertocarroll** [comment]
Thanks for the png. I haven't quite got the spacing right, but take a look at the site now. 

The issue is around the position of the logo when the nav is up against the top of the browser. 

Take a look at another pages as well - I think it would look odd with a bit of white space above the nav to accommodate the logo ... but open to ideas / suggestions ...

**Comment by clintmclean** [comment]
I agree the stripe is a bit odd though I think this way is also.

**Comment by UnaJanicijevic** [comment]
Hey guys.
We definitely don't need it on the opening page since we have the full logo above.
I'm sending you a version with the WATF letters a little heavier, so it could stand to be smaller. Maybe it just hangs below not above? I think that would work.
![logo-smallb](https://f.cloud.github.com/assets/4991415/805499/de9d3644-ee27-11e2-8c80-de1cc70eea2e.png)
![screen shot 2013-07-16 at 10 57 31 am](https://f.cloud.github.com/assets/4991415/805509/151ad42e-ee28-11e2-8d88-bb4374fc4b1b.png)

Also, there is this option?????
![screen shot 2013-07-16 at 10 50 06 am](https://f.cloud.github.com/assets/4991415/805497/d555de88-ee27-11e2-9ce2-c543da525ed1.png)

**Comment by robertocarroll** [comment]
I've taken the size down and used the new logo (thanks!) 

I think there's an argument for it being on the homepage as a Back to top in the fixed nav ...

**Comment by UnaJanicijevic** [comment]
I think it's working well.
Hmm, I see your point about it staying in the nav all the time, it's useful. But it looks strange when next to the big logo.... Clint what say you?

**Comment by UnaJanicijevic** [comment]
In light of this, and let's say we keep the mini nav logo, I would propose a simpler footer.
No need for that honking logo there. I think contact info will suffice. Fun facts... staying or going?

Something like this..

![screen shot 2013-07-16 at 6 11 58 pm](https://f.cloud.github.com/assets/4991415/808475/de665740-ee64-11e2-911c-7aa5deb3ea52.png)

**Comment by robertocarroll** [comment]
That looks nice and it would work as a footer for the rest of the site, but on the homepage the contact section needs to be quite deep (lots of height) so that it works with the scroll-to nav ... (see how it doesn't work at the moment)

**Comment by clintmclean** [comment]
I agree the repeated logo on the top of the home page looks weird. Is it possible to not have it there but to include it once you scroll down to the next section? I really preferred the thinner nav bar also but I guess if you two like the thick then that's fine. 

Rob I see what you mean about the footer - if we click 'contact us' and it takes us to the footer, it needs to be apparent we have been taken to the footer and not the section above it. Can we make it bigger? Maybe add the interesting facts back in? I liked that idea. 

OR what about using the little icons like in the footer (facebook etc) below our bios and that could include and email and phone icon for each of us. That could then be the About Us/Contact section. Just a thought.

**Comment by robertocarroll** [comment]
Issue #19 deals with the contact and the scroll to ... I'm closing this issue now.
