### ISSUE TITLE
Alternating work / quote posts as in design

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/wearethoughtfox-wp#8]
I had a quick look at how to do this, but it is going to take quite a lot of work to implement. So I've gone with a straight four work posts for now. 

I will return to this issue once we get everything else done.

**Comment by clintmclean** [comment]
could we perhaps not have 'work type' and a 'quote type' boxes but rather just one kind and the quotes are uploaded as images? Not sure how it will look since jpgs aren't great for text and pdf's won't upload (correct?).

**Comment by UnaJanicijevic** [comment]
Yea I say, if we need a quick workaround, we just do it with images. (unless you object Rob).
I think it's an important element to preserve.

**Comment by robertocarroll** [comment]
I will be able to do it, but it's something I'd rather not spend time on doing in a hacky way and then have to re-do in the proper way ... rather just do the proper way to start with ... if that's OK ...

**Comment by clintmclean** [comment]
yes proper way is preferred. Sorry I thought it was causing problems.

**Comment by robertocarroll** [comment]
To clarify: I won't be able to do it in time for launch in eight days. 

I will be able to do it ... at some point after that (when I get back from holiday).

**Comment by clintmclean** [comment]
I guess the question then becomes do we just do it as a grid of content or do we rethink the idea? Is the grid interesting enough? Maybe. 
When we launch we have the most power to get people to look at the site because we can mail everyone letting them know of the new venture and website. I think it's important to have it looking really strong at this point since it will be the biggest burst of traffic we get to the site.

So - do we think a gird is fine or does it need a little rethink?

**Comment by robertocarroll** [comment]
Or I could just remove that section for now and only Barjeel on the front and a link below to more work ...

**Comment by clintmclean** [comment]
Do you think that is maybe a missed opportunity to highlight a few works on the main page?

**Comment by robertocarroll** [comment]
Yes it would be a loss. I'm not saying not have it at all, just not for launch in 5 days.

**Comment by robertocarroll** [comment]
Let's park this one for now. Closing this issue, but will revisit.

**Comment by robertocarroll** [comment]
Moving this to the next sprint.
