### ISSUE TITLE
Formats and sizes for imagery 

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/wearethoughtfox-wp#9]

**Comment by UnaJanicijevic** [comment]
What do you guys think of the dimensions of the boxes provided in the InDesign file?

**Comment by UnaJanicijevic** [comment]
We should also have a standard look for digital projects in particular, like the Barjeel site on the imac screen, and/or tablet, phone...
I am happy to build these if you guys send me your images.

**Comment by clintmclean** [comment]
I think we need to keep the proportions of the indesign file but decide on max px sizes yes? The proportion will not change but will scale down from largest practical screen. What is the largest screen we want to cater to?

**Comment by clintmclean** [comment]
Maybe we should do the non-featured work in tablet rather than iMac since the iMac takes up a fair bit of room?
I like the idea of showing a mobile maybe with either/both as well.

**Comment by UnaJanicijevic** [comment]
Oh, I thought 960px was the largest. That's what the InDesign file is set to.
Which makes the large featured image 717px x 500px.
/////
Good idea. iMac for featured, iPad for the others.

**Comment by clintmclean** [comment]
Let's see what Rob says. Images can scale up (as they do on Barjeel) past the 960 px frame size but the text doesn't scale so I don't know where we just let the image start to fall apart - at 961 or do we let it go further even though the text doesn't scale?

**Comment by robertocarroll** [comment]
Hi. I'm struggling to unpick the main points from the thread above but here goes:  

The grid works in percentages/proportions, but it uses particular breakpoints in pixels, eg: 

$break-mobile: 480px;
$break-tablet: 768px;
$break-desktop: 1100px;
$break-bigscreen: 1300px;

This approach is OK, but it doesn't really get the the heart of the issue which is designing around the content rather than a particular set of devices. So the question really should start from the content ... You both probably know a lot more about this kind of thing, but it's important to transpose your expertise to develop for a range of rapidly changing devices ... ie iPad is a certain width now, but in a couple of years might be different. 

As for images, the images can be cropped or resized to certain pixel dimension and then a width: 100%, height: auto ; keeps them in scale. A max-width will stop them going past the biggest width and getting blurry. 

Hope this answers your question ... long discussions to be had here ...

**Comment by clintmclean** [comment]
Hi - yeah I get the 100% thing. No problem.
We just need actual dimensions for max sizes because we can't design or size images in percentages - they need to have px dimensions. So are you suggesting we start doing 4 screen size designs?

**Comment by robertocarroll** [comment]
I don't think we should do four designs. I think we should do one. It's a matter of allowing the content and user needs for a particular project dictate the approach and then tweaking that design for the rest within the tolerances of the time and budget.

**Comment by robertocarroll** [comment]
I think we've covered this in the hangout so closing, but feel free to re-open if not clear.
